name: 文章PDF生成

on:
  push:
    branches:
      - test
  schedule:
    - cron: '0 0 * * 1'  # 每周一零点
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Generate-Artical-PDF:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3


      - name: Install Pandoc & TexLive
        run: |
          sudo apt-get update
          # 安装 pandoc
          sudo apt-get install -y pandoc
          # 安装 XeLaTeX 引擎和中文语言包 (比完整版 texlive 小很多)
          sudo apt-get install -y texlive-xetex texlive-lang-chinese texlive-fonts-recommended texlive-latex-extra
          # 安装中文字体 (思源黑体)
          sudo apt-get install -y fonts-noto-cjk
          
          

      - name: Generate PDFs and Mapping.json
        run: bash .github/scripts/incremental-pdf.sh

      - name: Commit and Push changes
        run: |
          # 配置 Git 用户信息
          git config --global user.name 'xbzhong'
          git config --global user.email '2396768163@qq.com'
          
          git add .github/mapping/mapping.json
          git add docs

          # 检查是否有变更，有则提交
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected, committing..."
            # [skip ci] 很重要，防止 push 后再次触发 workflow 导致死循环
            git commit -m "chore(pdf): update generated PDFs and mapping [skip ci]"
            git push origin test
          else
            echo "No changes to commit."
          fi


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Email HTML
        run: python .github/scripts/pdf-json2email.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "博客PDF更新报告"
          to: "2396768163@qq.com"
          from: "Github Action <${{ secrets.MAIL_USERNAME }}>"
          html_body: file://email.html
