name: 文章PDF生成

on:
  push:
    branches:
      - test
  schedule:
    - cron: '0 0 * * 1'  # 每周一零点
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Generate-Artical-PDF:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3


      - name: Generate PDFs and Mapping.json
        run: bash .github/scripts/incremental-pdf.sh

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Email HTML
        run: python scripts/pdf-json2email.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "博客PDF更新报告"
          to: "2396768163@qq.com"
          from: "Github Action <${{ secrets.MAIL_USERNAME }}>"
          html_body: file://email.html
